language: node_js

sudo: required
services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test:ci
  - npm run lint
  - npm run lint:sonar
  - npm run build
  - echo "WIREMOCK_PORT=3001" > ./mock_tools/.env
  - docker-compose -f ./mock_tools/docker-compose.yml up --build -d
  - sleep 30
  - docker-compose -f ./mock_tools/docker-compose.yml rm --force --stop -v

after_script:
  - ./cc-test-reporter upload-coverage --id $TRAVIS_COMMIT --input ./reports/coverage/lcov.info
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
