version: '3'

services:
  wiremock:
    build:
      context: ./@mock_toolkit/wiremock
    container_name: react.wiremock
    env_file:
      - .env
    volumes:
      - ./@mock_toolkit/wiremock/data:/wiremock/data
    ports:
      - ${WIREMOCK_PORT}:3001

  wiremock_reloader:
    build:
      context: ./@mock_toolkit/wiremock-auto-reloader
    container_name: react.wiremock_reloader
    env_file:
      - .env
    volumes:
      - ./@mock_toolkit/wiremock/data:/wiremock/data
    depends_on:
      - wiremock

  devserver:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: react.devserver
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - ${DEV_SERVER_PORT}:3000
