version: '3.8'

services:
  dev-app:
    build:
      context: ./
      dockerfile: ../../build/docker/Dockerfile.dev
    container_name: react.dev-app
    env_file:
      - .env
    volumes:
      - ../../:/app
    ports:
      - ${DEV_SERVER_PORT}:3000

  dev-storybook:
    build:
      context: ./
      dockerfile: ../../build/docker/Dockerfile.dev
    container_name: react.dev-storybook
    env_file:
      - .env
    volumes:
      - ../../:/app
    ports:
      - ${STORYBOOK_PORT}:9009
    command: yarn start-storybook -p ${STORYBOOK_PORT}
