version: '3'

# Docker Compose responsible to bring up a Mock Server environment based on WireMock
# It starts a re-loader tool to make scenarios simulation easier

services:
  wiremock:
    build:
      context: ./wiremock
    container_name: local_wiremock
    env_file:
      - .env
    volumes:
      - ./wiremock/data:/wiremock/data
    ports:
      - ${WIREMOCK_PORT}:3001

  wiremock_reloader:
    build:
      context: ./wiremock_reloader
    container_name: local_wiremock_reloader
    env_file:
      - .env
    volumes:
      - ./wiremock/data:/wiremock/data
    depends_on:
      - wiremock
