version: '2'

services:
  wiremock:
    build:
      context: ./wiremock
    container_name: local_wiremock
    env_file:
      - .env
    volumes:
      - ./wiremock/data:/wiremock/data
    ports:
      - 3001:3001

  wiremock_reloader:
    build:
      context: ./wiremock_reloader
    container_name: local_wiremock_reloader
    env_file:
      - .env
    volumes:
      - ./wiremock/data:/wiremock/data
    depends_on:
      - wiremock
